threshold: 0.4
threshold_angle: 0.4
wp:
    - {x: 0, y: 5, z: -4, theta: -1.05}
    - {x: 1, y: 5, z: -4, theta: -1.05}
    - {x: 2, y: 5, z: -4, theta: -1.05}
    - {x: 3, y: 5, z: -4, theta: -1.05}
    - {x: 4, y: 5, z: -4, theta: -1.05}
    
